automation:
  - alias: 'Send notification when alarm triggered'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_langepad
        to: 'triggered'
    action:
      - service: notify.douwe
        data:
          message: "ALARM! iets gedetecteerd"
          title: "Alarm"

  - alias: 'Trigger alarm while armed away' 
    trigger:
      - platform: state
        entity_id: binary_sensor.hal_sensor_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bijkeuken_sensor_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.toilet_sensor_motion
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
        above: 7
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_langepad
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm_langepad

  - alias: 'Arw while away'
    trigger:
      - platform: state
        entity_id: group.all_devices
        to: 'not_home'
    action:
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.alarm_langepad
          code: !secret alarm_code
      - service: notify.douwe
        data:
          message: "Iedereen afwezig"
          title: "Alarm ingeschakeld"

  - alias: 'Disarm while home'
    trigger:
      - platform: state
        entity_id: group.all_devices
        to: 'home'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.alarm_langepad
          code: !secret alarm_code
      - service: notify.douwe
        data:
          message: "Iemand is thuis"
          title: "Alarm uitgeschakeld"

  - alias: "Sunset"
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      - service: script.sunset_script

  - alias: "Lights off automatic"
    trigger:
      platform: time
      at: "23:00:00"
    condition:
      - condition: state
        entity_id: 'group.all_devices'
        state: 'not_home'
    action:
      - service: script.activate_slapen_gaan


  - alias: 'morning kitchen light' 
    trigger:
      - platform: numeric_state
        entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
        above: 7
    condition:
      condition: time
      # At least one of the following is required.
      after: '05:30:00'
      before: '08:30:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: script.morning_routine

